### ISSUE TITLE
join: problem with joinby

### ISSUE THREAD

**Issue by eirinistam** [akaitoua/GMQL#9] opened 2017-02-25 20:38 UTC
I did the below queries with joinby and without and i had the same results.
Example1:
HM_TSS = JOIN(MD(1), DGE(50); output: RIGHT)TSS HSS;
Given a dataset HSS of ChIP-seq experiment samples regarding Histone Modifications and one called TSS with a sample including Transcription Start Site annotations, this GMQL statement searches for those regions of HSS that are at a minimal distance from a transcription start site (TSS) and takes the first/closest one for each TSS, provided that such distance is greater than 50 basesand joined TSS and HSS samples. Note: The joinby didn’t work.

Example2:
HM_TSS = JOIN(MD(1), DGE(50); output:CAT)TSS HSS;
This example includes the same input datasets, genometric predicate as Example 1, but the output is produced as the concatenation of regions selected by the genometric predicate .Note: the joinby didn’t work

example1: https://www.dropbox.com/sh/i9sgoc2gzglfds3/AACNfcxHCxm67xXKqgL4gLQma?dl=0
example2:https://www.dropbox.com/sh/30wgmwb8wmjhpb1/AACO05iJGAk5mSlp0cQxLlPsa?dl=0

**Comment by OlgaGorlova** [comment] 2017-02-26 20:44
I also faced with this issue. It looks like it is caused by the compiler - it sets incorrect OptionalMetaJoinOperator for JOIN operator (NoMetaJoinOperator instead of SomeMetaJoinOperator). Pietro, can you check this, please? @pp86

**Comment by pp86** [comment] 2017-02-26 22:05
I committed a change in the code

**Closed** 2017-03-02 13:35 UTC
